POST http://localhost:3333/transactions
Content-Type: application/json

{
    "who": "Vagner",
    "company": "copel",
    "value": 300,
    "date": "2026-06-30T00:00:00.000Z",
    "type": "expense"
}

###

POST http://localhost:3333/transactions
Content-Type: application/json

{
    "who": "Lovane",
    "company": "Mercado",
    "value": 100,
    "date": "2026-06-01T00:00:00.000Z",
    "type": "expense"
}

###

GET http://localhost:3333/transactions
Content-Type: application/json

###

GET http://localhost:3333/transactions/summary
Content-Type: application/json




